import { GoogleGenAI } from '@google/genai';

export interface ExtractedChapter {
  startSeconds: number;
  endSeconds: number;
  title: string;
  formattedStart: string;
  formattedEnd: string;
  formattedDuration: string;
  thumbnailUrl?: string;
  isAutoGenerated: boolean;
  source: 'creator' | 'youtube_auto' | 'ai_generated';
}

function formatSeconds(sec: number): string {
  const s = Math.max(0, Math.floor(sec));
  const hours = Math.floor(s / 3600);
  const minutes = Math.floor((s % 3600) / 60);
  const seconds = s % 60;

  if (hours > 0) {
    return `${hours}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
  }
  return `${minutes}:${seconds.toString().padStart(2, '0')}`;
}

function parseTimestampToSeconds(timestampStr: string): number | null {
  if (!timestampStr) return null;
  const parts = timestampStr.trim().split(':').map((p) => Number(p));
  if (parts.some((p) => isNaN(p) || p < 0)) return null;

  if (parts.length === 3) {
    const [hours, minutes, seconds] = parts;
    if (minutes >= 60 || seconds >= 60) return null;
    return hours * 3600 + minutes * 60 + seconds;
  } else if (parts.length === 2) {
    const [minutes, seconds] = parts;
    if (seconds >= 60) return null;
    return minutes * 60 + seconds;
  }
  return null;
}

export function parseDescriptionChapters(
  description: string | undefined | null,
  videoDurationSeconds?: number,
  videoId?: string
): ExtractedChapter[] {
  if (!description || typeof description !== 'string' || description.trim().length === 0) {
    return [];
  }

  const lines = description.split(/\r?\n/);
  const rawList: { startSeconds: number; title: string; formattedStart: string }[] = [];

  for (const line of lines) {
    const trimmedLine = line.trim();
    if (!trimmedLine || trimmedLine.length < 3) continue;

    // Filter non-timestamps
    if (/^(https?:\/\/|git clone|npm i|npm install|cd |yarn add|docker |curl |const |import |from )/i.test(trimmedLine)) {
      continue;
    }
    if (/\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d{2,5}\b/.test(trimmedLine)) {
      continue;
    }

    const timestampRegex = /(?:\[|\(|\b)?(?:(\d{1,2}):)?(\d{1,2}):(\d{2})(?:\]|\)|\b)?/;
    const match = trimmedLine.match(timestampRegex);
    if (!match) continue;

    const rawFullMatch = match[0];
    const cleanTimestamp = rawFullMatch.replace(/[^\d:]/g, '');
    const startSeconds = parseTimestampToSeconds(cleanTimestamp);
    if (startSeconds === null || startSeconds < 0) continue;
    if (videoDurationSeconds && videoDurationSeconds > 0 && startSeconds >= videoDurationSeconds) {
      continue;
    }

    let title = trimmedLine.replace(rawFullMatch, ' ');
    title = title.replace(/^[\(\[\{]/, '').replace(/[\)\]\}]$/, '');
    title = title.replace(/^(?:chapter\s+\d+[\s:\-—–|]*|\d+[\.\)\-—–:]\s*|#\d+\s*)/i, '');
    title = title.replace(/^[–—\-\|\:\•\.\~\s\t\/\#\*\>]+|[–—\-\|\:\•\.\~\s\t\/\#\*\>]+$/g, '').trim();

    if (!title || title.length === 0) {
      title = `Section at ${cleanTimestamp}`;
    }

    rawList.push({
      startSeconds,
      title,
      formattedStart: formatSeconds(startSeconds),
    });
  }

  if (rawList.length === 0) return [];

  rawList.sort((a, b) => a.startSeconds - b.startSeconds);

  // Deduplicate
  const deduplicated: { startSeconds: number; title: string; formattedStart: string }[] = [];
  for (const item of rawList) {
    const existingIndex = deduplicated.findIndex((d) => d.startSeconds === item.startSeconds);
    if (existingIndex >= 0) {
      if (item.title.length > deduplicated[existingIndex].title.length) {
        deduplicated[existingIndex] = item;
      }
    } else {
      deduplicated.push(item);
    }
  }

  if (deduplicated.length < 2 && (videoDurationSeconds || 0) > 180) {
    // Only 1 timestamp in description might just be an intro note, not full curriculum
    return [];
  }

  const effectiveDuration = videoDurationSeconds && videoDurationSeconds > 0 ? videoDurationSeconds : 0;
  const defaultThumb = videoId ? `https://img.youtube.com/vi/${videoId}/mqdefault.jpg` : undefined;

  return deduplicated.map((ch, index) => {
    let endSec = 0;
    if (index < deduplicated.length - 1) {
      endSec = deduplicated[index + 1].startSeconds;
    } else {
      endSec = effectiveDuration > ch.startSeconds ? effectiveDuration : ch.startSeconds + 60;
    }
    const durationSec = Math.max(0, endSec - ch.startSeconds);

    return {
      startSeconds: ch.startSeconds,
      endSeconds: endSec,
      title: ch.title,
      formattedStart: ch.formattedStart,
      formattedEnd: formatSeconds(endSec),
      formattedDuration: formatSeconds(durationSec),
      thumbnailUrl: defaultThumb,
      isAutoGenerated: false,
      source: 'creator',
    };
  });
}

/**
 * Extracts YouTube's auto-generated chapters from the watch page / innertube metadata.
 */
export async function extractYouTubeWatchChapters(
  videoId: string,
  videoDurationSeconds?: number
): Promise<ExtractedChapter[]> {
  try {
    const res = await fetch(`https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}`, {
      headers: {
        'User-Agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept-Language': 'en-US,en;q=0.9',
      },
    });

    if (!res.ok) {
      return [];
    }

    const html = await res.text();

    const ytInitialDataMatch =
      html.match(/ytInitialData\s*=\s*({.+?});<\/script>/s) ||
      html.match(/var ytInitialData\s*=\s*({.+?});/s);

    if (!ytInitialDataMatch) {
      return [];
    }

    const data = JSON.parse(ytInitialDataMatch[1]);
    const rawList: { startSeconds: number; title: string; formattedStart?: string; thumbnailUrl?: string }[] = [];

    function traverse(obj: any) {
      if (!obj || typeof obj !== 'object') return;

      // Handle macroMarkersListItemRenderer (Standard YouTube Chapter Renderers)
      if (obj.macroMarkersListItemRenderer) {
        const item = obj.macroMarkersListItemRenderer;
        const title = item.title?.simpleText || item.title?.runs?.map((r: any) => r.text).join('') || '';
        const timeDesc =
          item.timeDescription?.simpleText ||
          item.timeDescription?.runs?.map((r: any) => r.text).join('') ||
          '';

        let startSec: number | undefined = item.onTap?.watchEndpoint?.startTimeSeconds;
        if (startSec === undefined && item.timeDescriptionEntryPoint?.commandMetadata?.webCommandMetadata?.url) {
          const m = item.timeDescriptionEntryPoint.commandMetadata.webCommandMetadata.url.match(/t=(\d+)s?/);
          if (m) startSec = parseInt(m[1], 10);
        }
        if (startSec === undefined && timeDesc) {
          const parsed = parseTimestampToSeconds(timeDesc);
          if (parsed !== null) startSec = parsed;
        }

        const thumbUrl =
          item.thumbnail?.thumbnails?.[item.thumbnail.thumbnails.length - 1]?.url ||
          item.thumbnail?.thumbnails?.[0]?.url;

        if (startSec !== undefined && title && startSec >= 0) {
          rawList.push({
            startSeconds: startSec,
            title: title.trim(),
            formattedStart: timeDesc || formatSeconds(startSec),
            thumbnailUrl: thumbUrl,
          });
        }
      }

      // Handle chapterRenderer
      if (obj.chapterRenderer) {
        const item = obj.chapterRenderer;
        const title = item.title?.simpleText || item.title?.runs?.map((r: any) => r.text).join('') || '';
        let startSec = 0;
        if (item.timeRangeStartMillis !== undefined) {
          startSec = Math.floor(Number(item.timeRangeStartMillis) / 1000);
        }
        const thumbUrl =
          item.thumbnail?.thumbnails?.[item.thumbnail.thumbnails.length - 1]?.url ||
          item.thumbnail?.thumbnails?.[0]?.url;

        if (title && startSec >= 0) {
          rawList.push({
            startSeconds: startSec,
            title: title.trim(),
            formattedStart: formatSeconds(startSec),
            thumbnailUrl: thumbUrl,
          });
        }
      }

      // Handle timedMarkerDecorations (filter out 'Most replayed' or non-chapter heatmap markers)
      if (obj.timedMarkerDecorations && Array.isArray(obj.timedMarkerDecorations)) {
        for (const marker of obj.timedMarkerDecorations) {
          const title = (marker.label?.simpleText || marker.label?.runs?.map((r: any) => r.text).join('') || '').trim();
          if (!title || /^most replayed$/i.test(title) || /^heatmap/i.test(title)) {
            continue;
          }
          const startOffsetMs = marker.visibleTimeRangeStartMillis || marker.startOffsetMs;
          if (title && startOffsetMs !== undefined) {
            const startSec = Math.floor(Number(startOffsetMs) / 1000);
            rawList.push({
              startSeconds: startSec,
              title: title.trim(),
              formattedStart: formatSeconds(startSec),
            });
          }
        }
      }

      for (const k in obj) {
        if (Object.prototype.hasOwnProperty.call(obj, k)) {
          traverse(obj[k]);
        }
      }
    }

    traverse(data);

    if (rawList.length === 0) {
      return [];
    }

    rawList.sort((a, b) => a.startSeconds - b.startSeconds);

    // Deduplicate
    const deduplicated: { startSeconds: number; title: string; formattedStart: string; thumbnailUrl?: string }[] = [];
    for (const item of rawList) {
      const existingIndex = deduplicated.findIndex((d) => d.startSeconds === item.startSeconds);
      if (existingIndex >= 0) {
        if (item.title.length > deduplicated[existingIndex].title.length) {
          deduplicated[existingIndex] = {
            startSeconds: item.startSeconds,
            title: item.title,
            formattedStart: item.formattedStart || formatSeconds(item.startSeconds),
            thumbnailUrl: item.thumbnailUrl || deduplicated[existingIndex].thumbnailUrl,
          };
        }
      } else {
        deduplicated.push({
          startSeconds: item.startSeconds,
          title: item.title,
          formattedStart: item.formattedStart || formatSeconds(item.startSeconds),
          thumbnailUrl: item.thumbnailUrl,
        });
      }
    }

    if (deduplicated.length === 0) return [];

    const effectiveDuration = videoDurationSeconds && videoDurationSeconds > 0 ? videoDurationSeconds : 0;
    const defaultThumb = `https://img.youtube.com/vi/${videoId}/mqdefault.jpg`;

    return deduplicated.map((ch, index) => {
      let endSec = 0;
      if (index < deduplicated.length - 1) {
        endSec = deduplicated[index + 1].startSeconds;
      } else {
        endSec = effectiveDuration > ch.startSeconds ? effectiveDuration : ch.startSeconds + 60;
      }
      const durationSec = Math.max(0, endSec - ch.startSeconds);

      return {
        startSeconds: ch.startSeconds,
        endSeconds: endSec,
        title: ch.title,
        formattedStart: ch.formattedStart,
        formattedEnd: formatSeconds(endSec),
        formattedDuration: formatSeconds(durationSec),
        thumbnailUrl: ch.thumbnailUrl || defaultThumb,
        isAutoGenerated: true,
        source: 'youtube_auto',
      };
    });
  } catch (err) {
    console.warn(`Could not extract YouTube watch chapters for ${videoId}:`, err);
    return [];
  }
}

/**
 * Intelligent topic milestone chapters using Gemini when no chapters exist in description or YouTube
 */
export async function generateAiChapters(
  title: string,
  description: string,
  durationSeconds: number,
  videoId?: string
): Promise<ExtractedChapter[]> {
  const geminiApiKey = process.env.GEMINI_API_KEY?.trim();
  if (!geminiApiKey || durationSeconds < 180) {
    return [];
  }

  try {
    const ai = new GoogleGenAI({ apiKey: geminiApiKey });
    const durationMinutes = Math.round(durationSeconds / 60);

    const prompt = `You are a learning curriculum generator. Break down this instructional educational video into clear, structured logical chapters/milestones.

Video Details:
- Title: "${title}"
- Total Duration: ${durationMinutes} minutes (${durationSeconds} seconds)
- Description / Syllabus: "${(description || '').slice(0, 1500)}"

Requirements:
1. Divide the video into 4 to 8 logical chapter timestamps starting from 0 (0:00).
2. Each chapter must have:
   - "startSeconds" (integer, must be strictly < ${durationSeconds})
   - "title" (concise, clear topic name, max 6-8 words)
3. Ensure timestamps are strictly increasing and distributed realistically across the ${durationMinutes} minutes.

Return ONLY a JSON array strictly matching this format:
[
  { "startSeconds": 0, "title": "Introduction & Overview" },
  { "startSeconds": 180, "title": "Key Principles & Theory" }
]`;

    const candidateModels = ['gemini-3.6-flash', 'gemini-3.7-flash', 'gemini-2.0-flash', 'gemini-1.5-flash'];
    let responseText: string | undefined = undefined;

    for (const modelName of candidateModels) {
      try {
        const response = await ai.models.generateContent({
          model: modelName,
          contents: prompt,
          config: {
            responseMimeType: 'application/json',
          },
        });
        if (response && response.text) {
          responseText = response.text.trim();
          break;
        }
      } catch (err: any) {
        // Continue to next active candidate model
      }
    }

    if (!responseText) {
      return [];
    }
    let parsed: any[];
    try {
      parsed = JSON.parse(responseText);
    } catch {
      const cleanJson = responseText.replace(/```json/g, '').replace(/```/g, '').trim();
      parsed = JSON.parse(cleanJson);
    }

    if (!Array.isArray(parsed) || parsed.length === 0) {
      return [];
    }

    parsed.sort((a, b) => (a.startSeconds || 0) - (b.startSeconds || 0));
    const defaultThumb = videoId ? `https://img.youtube.com/vi/${videoId}/mqdefault.jpg` : undefined;

    const result: ExtractedChapter[] = parsed
      .filter((p) => typeof p.startSeconds === 'number' && p.startSeconds >= 0 && p.startSeconds < durationSeconds)
      .map((p, idx, arr) => {
        const startSec = p.startSeconds;
        let endSec = durationSeconds;
        if (idx < arr.length - 1) {
          endSec = arr[idx + 1].startSeconds;
        }
        const durationSec = Math.max(0, endSec - startSec);
        return {
          startSeconds: startSec,
          endSeconds: endSec,
          title: (p.title || `Section ${idx + 1}`).trim(),
          formattedStart: formatSeconds(startSec),
          formattedEnd: formatSeconds(endSec),
          formattedDuration: formatSeconds(durationSec),
          thumbnailUrl: defaultThumb,
          isAutoGenerated: true,
          source: 'ai_generated',
        };
      });

    return result;
  } catch (e) {
    console.warn('AI chapter generation failed:', e);
    return [];
  }
}

/**
 * Universal chapter resolver: checks creator description -> YouTube auto markers -> AI generation.
 */
export async function resolveVideoChapters(params: {
  videoId: string;
  description?: string;
  durationSeconds?: number;
  title?: string;
}): Promise<{ chapters: ExtractedChapter[]; source: 'creator' | 'youtube_auto' | 'ai_generated' | 'none' }> {
  const { videoId, description = '', durationSeconds = 0, title = '' } = params;

  // 1. Try creator description chapters first
  const creatorChapters = parseDescriptionChapters(description, durationSeconds, videoId);
  if (creatorChapters.length >= 2) {
    return {
      chapters: creatorChapters,
      source: 'creator',
    };
  }

  // 2. Try YouTube Auto-generated Chapters from watch page metadata
  const ytAutoChapters = await extractYouTubeWatchChapters(videoId, durationSeconds);
  if (ytAutoChapters.length >= 1) {
    return {
      chapters: ytAutoChapters,
      source: 'youtube_auto',
    };
  }

  // If creator had only 1 single chapter (e.g. at 0:00), we can still use it if auto failed
  if (creatorChapters.length === 1) {
    return {
      chapters: creatorChapters,
      source: 'creator',
    };
  }

  // 3. If no chapters exist and video is long enough, generate AI chapters
  if (durationSeconds >= 240 && title) {
    const aiChapters = await generateAiChapters(title, description, durationSeconds, videoId);
    if (aiChapters.length >= 2) {
      return {
        chapters: aiChapters,
        source: 'ai_generated',
      };
    }
  }

  return {
    chapters: [],
    source: 'none',
  };
}
