export interface AiStudyPlanRecommendation {
  recommendedDailyHours: number;
  recommendedDailyMinutes: number;
  recommendedDays: number;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced' | 'Intensive';
  pacingRationale: string;
  studyTips: string[];
  isFallback?: boolean;
  generatedAt?: string;
}

export type ScheduleDay = 'Mon' | 'Tue' | 'Wed' | 'Thu' | 'Fri' | 'Sat' | 'Sun';
export type ScheduleMode = 'daily' | 'custom' | 'none' | 'self-paced';

export interface CourseStudySchedule {
  mode: ScheduleMode;
  customDays?: ScheduleDay[]; // e.g. ['Sat', 'Sun'] or ['Mon', 'Wed', 'Fri']
  scheduledDays?: string[]; // alias support for custom days
  dailyGoalMinutes: number; // e.g. 60 min (1 hr/day)
  updatedAt?: string;
}

export interface CourseStudyGoal {
  dailyQuotaMinutes: number; // e.g. 60 min = 1 hr/day
  dailyQuotaHours: number; // e.g. 1.0
  initialStartDate: string; // ISO / YYYY-MM-DD string when course was enrolled
  initialTargetDeadline: string; // ISO / YYYY-MM-DD calculated initially based on quota
  initialTotalDays: number; // Initial estimated days
  schedule?: CourseStudySchedule;
  aiRecommendation?: AiStudyPlanRecommendation;
  updatedAt?: string;
}

export interface CourseDeadlinePacing {
  status: 'ahead' | 'on_track' | 'behind' | 'completed_early' | 'completed_on_time' | 'completed_late';
  daysDelta: number; // < 0 means ahead of schedule (e.g. -3 days), > 0 means delayed/behind schedule (e.g. +4 days)
  initialTargetDeadline: string; // YYYY-MM-DD
  initialTargetDeadlineFormatted: string; // e.g. "Oct 15, 2026"
  currentEstimatedDeadline: string; // YYYY-MM-DD
  currentEstimatedDeadlineFormatted: string; // e.g. "Oct 12, 2026"
  currentProjectedDeadlineFormatted?: string; // alias for display
  daysLeftCurrentPace: number;
  initialTotalDays: number;
  dailyQuotaMinutes: number;
  dailyQuotaHours: number;
  hoursNeededDailyToHitInitialDeadline: number; // catch-up required if behind
  minutesNeededDailyToHitInitialDeadline: number;
  pacingMessage: string;
  badgeText: string;
  praiseOrAlertLevel: 'praise' | 'neutral' | 'warning' | 'alert' | 'success';
  isCompleted: boolean;
  studySchedule?: CourseStudySchedule;
  isScheduledToday?: boolean;
  scheduleSummary?: string | null;
  scheduleStatusLabel?: string;
  expectedWeeklyMinutes?: number;
  expectedWeeklyHours?: number;
}

export interface Course {
  id: string; // playlistId or unique course id
  playlistId: string;
  title: string;
  description: string;
  channelTitle: string;
  thumbnail: string;
  totalVideos: number;
  completedVideos: number;
  percentage: number;
  totalDurationSeconds: number;
  isBookmarked?: boolean;
  studyGoal?: CourseStudyGoal;
  studySchedule?: CourseStudySchedule;
  createdAt: string;
  updatedAt: string;
}

export interface CourseVideo {
  id: string; // videoId
  courseId: string;
  title: string;
  description: string;
  thumbnail: string;
  channelTitle: string;
  position: number;
  durationSeconds: number;
  durationFormatted: string;
  isBookmarked?: boolean;
}

export interface VideoProgress {
  userId: string;
  courseId: string;
  videoId: string;
  videoTitle?: string;
  videoThumbnail?: string;
  courseTitle?: string;
  channelTitle?: string;
  watchedSeconds: number;
  durationSeconds: number;
  percentage: number;
  completed: boolean;
  completionSource?: 'manual' | 'auto';
  watchedSegments?: [number, number][]; // [startSeconds, endSeconds] pairs
  lastWatchedAt: string;
  updatedAt: string;
}

export interface UserStats {
  totalCourses: number;
  completedVideos: number;
  totalWatchSeconds: number;
  overallProgress: number;
  currentStreak: number;
  bestStreak: number;
  lastActiveDate: string;
  activeDates: string[]; // List of YYYY-MM-DD
}

export interface UserProfile {
  uid: string;
  email: string | null;
  displayName: string | null;
  photoURL: string | null;
  isAnonymous: boolean;
}

export type ThemeMode = 'dark' | 'light' | 'system';

export interface YouTubeChapter {
  startSeconds: number;
  endSeconds: number;
  title: string;
  formattedStart: string;
  formattedEnd: string;
  formattedDuration: string;
  thumbnailUrl?: string;
  isAutoGenerated?: boolean;
  source?: 'creator' | 'youtube_auto' | 'ai_generated';
}

export interface YouTubePlayerState {
  status: 'UNSTARTED' | 'ENDED' | 'PLAYING' | 'PAUSED' | 'BUFFERING' | 'CUED' | 'NOT_READY' | 'ERROR';
  currentTime: number;
  duration: number;
  percentage: number;
  errorCode: number | null;
  errorMessage: string | null;
}

export interface AiCitation {
  title: string;
  url: string;
}

export interface AiCodeSnippet {
  language: string;
  code: string;
  title?: string;
  explanation?: string;
}

export interface AiAttachment {
  id: string;
  type: 'video-screenshot';
  dataUrl: string;
  videoId?: string;
  videoTitle?: string;
  timestampSeconds?: number;
  timestampFormatted?: string;
}

export interface DoubtContext {
  source: 'doubt-button';
  videoId: string;
  videoTitle: string;
  timestampSeconds: number;
  timestampFormatted: string;
  chapterTitle?: string;
  courseId: string;
}

export interface AiAssistantMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  attachments?: AiAttachment[];
  timestamp: string;
  actionType?: 'general' | 'summary' | 'code' | 'flowchart' | 'debug' | 'search';
  videoTimestampSeconds?: number;
  videoTimestampFormatted?: string;
  videoTitle?: string;
  citations?: AiCitation[];
  codeSnippets?: AiCodeSnippet[];
  flowchartMermaid?: string;
  isGenerating?: boolean;
  isFallback?: boolean;
  quotaNotice?: string;
  error?: string;
  timelineConfirmation?: {
    timeline: {
      label: string;
      startFormatted: string;
      endFormatted: string;
    };
    confirmed: boolean;
    originalRequestPrompt?: string;
    actionType?: 'general' | 'summary' | 'code' | 'flowchart' | 'debug' | 'search';
  };
}

export interface CourseAiMemory {
  courseId: string;
  courseTitle: string;
  messages: AiAssistantMessage[];
  watchedVideoSummaries: Record<string, string>; // videoId -> short takeaway
  savedNotes: Array<{
    id: string;
    videoId: string;
    videoTitle: string;
    timestampFormatted: string;
    note: string;
    createdAt: string;
  }>;
  lastUpdated: string;
}

export interface CodeExecutionResult {
  stdout: string;
  stderr: string;
  exitCode: number;
  executionTimeMs: number;
  error?: string;
}

export type CommitmentStatus = 'active' | 'paused' | 'cancelled' | 'completed';

export interface StudyCommitment {
  id: string; // The Firestore doc id
  userId: string;
  courseId: string;
  startDate: string; // YYYY-MM-DD
  endDate?: string; // YYYY-MM-DD (legacy/optional)
  initialExpectedCompletionDate?: string; // Historical baseline YYYY-MM-DD
  reminderTime: string; // e.g. "19:00"
  timezone: string; // e.g. "America/Los_Angeles"
  dailyTargetMinutes?: number; // e.g. 30 (legacy, now drawn from Course Schedule)
  status: CommitmentStatus;
  createdAt: string; // ISO
  pausedAt?: string; // ISO
  resumedAt?: string; // ISO
  cancelledAt?: string; // ISO
  completedAt?: string; // ISO
  googleTaskListId?: string;
  googleTaskId?: string;
}

export type DailyStudyStatus = 'COMPLETED' | 'MISSED' | 'PENDING' | 'FUTURE';

export interface StudyCommitmentDay {
  id: string; // YYYY-MM-DD
  commitmentId: string;
  userId: string;
  courseId: string;
  date: string; // YYYY-MM-DD
  status: DailyStudyStatus;
  targetMinutes: number;
  actualMinutes: number;
  completedAt?: string; // ISO
}

